spring:
  data:
    mongodb:
      database: customer
      port: 27017
      host: localhost
server:
  port: 8080
logging:
  file: customer/logs/logfile.log
serviceUrl:
  subscriber: https://localhost:8081