spring:
  data:
    mongodb:
      database: subscriber
      port: 27017
      host: localhost
server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
  session:
    cookie:
      secure: true
      http-only: true
logging:
  file: subscriber/logs/logfile.log
serviceUrl:
  customer: http://localhost:8080